services:
  nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
          - 80:80
      volumes:
          - ./config/nginx:/etc/nginx/conf.d/:rw
      networks:
          - odoo_network
  db:
    image: postgres:13
    restart: always
    container_name: postgresql
    command: -c config_file=/etc/postgresql.conf
    environment:
      - TZ=Asia/Jakarta
      - PGTZ=Asia/Jakarta
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./customPostgresql.conf:/etc/postgresql.conf
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh    
    secrets:
      - postgresql_password
    ports:
      - "5432:5432"
    networks:
      - odoo_network
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
